name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: 'ts'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-node@v4'
        with:
          node-version-file: 'ts/package.json'
      - run: npm ci
      - run: npm run ci
      - run: npm test
      - run: npm run build

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: 'actions/checkout@v4'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: hono-api-template:latest
          platforms: linux/amd64,linux/arm64
          context: 'ts'
          file: 'ts/Lambda.Dockerfile'

  renovate-check:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs:
      - test
      - build
    # See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#needs-context for result values
    if: ${{ cancelled() || failure() }}
    steps:
      - run: 'false'
